version: '3.4'

services:
  taxi-central-api:
    image: dmeshko/taxicentralapi:3.1
    build:
      context: .
      dockerfile: TaxiCentral.API/Dockerfile
    #environment:
    #  - ConnectionString="Server=tcp:127.0.0.1,5433;Database=TaxiCentral;User Id=sa;Password=P@ssw0rd;""
    #restart: unless-stopped
    ports:
      - "8080:80"  # Important: In a production environment your should remove the external port
      - "4443:443"  # Important: In a production environment your should remove the external port
    depends_on:
      - sql-server
    networks:
      - taxicentralnetwork

  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=P@ssw0rd
    restart: unless-stopped
    ports:
      - "5433:1433" # Important: In a production environment your should remove the external port
    networks:
      - taxicentralnetwork

networks:
  taxicentralnetwork:
    driver: "bridge"